---
title: "Species distributions vs. habitat loss"
author: "Petr Keil"
date: "July 22, 2016"
output: html_document
---

```{r}

  library(spatstat)
  library(raster)
  library(gstat)
```


# Generate Thomas process point data

```{r}
#  a <- rThomas(kappa=20, scale=0.03, mu=100) # Thomas process
  a <- rMatClust(kappa=20, scale=0.07, mu=200) # Matern cluster - contiguous blocks 
  x <- a$x
  y <- a$y
  xy <- cbind(x, y)
  
  ext <- extent(c(0,1,0,1))
  b <- raster(ext, nrow=100, ncol=100)
  b2 <- rasterize(x=xy, y=b, fun=function(x,...)length(x))
  b2 [b2 >=1] <- 1
    
  plot(b2)
```

# Fit Thomas model to the data
```{r}
  fit.a <- clusterfit(a, clusters="Thomas")
  fit.a$par
```

# Create a line segment pattern
```{r}
  example(psp) # line segment pattern
  
```

# Load Hansen's loss data

http://earthenginepartners.appspot.com/science-2013-global-forest/download_v1.2.html

```{r}
  download.file("https://storage.googleapis.com/earthenginepartners-hansen/GFC2015/Hansen_GFC2015_loss_00N_060W.tif", "loss.tiff")
  loss <- raster("loss.tiff")
  loss2 <- aggregate(loss, fact=10, fun=sum)
  loss3 <- aggregate(loss, fact=100, fun=sum)
  plot(loss3)
```





